Empezando con Python
--------------------

Nuevo con Python? Vamos a configurar correctamente tu ambiente Python.

.. toctree::
   :maxdepth: 2

   starting/which-python

- Instalación de Python

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install3/osx
    starting/install3/win
    starting/install3/linux
    starting/install/osx
    starting/install/win
    starting/install/linux


- Using Virtualenvs with Pipenv:

.. toctree::
    :maxdepth: 2

    dev/virtualenvs


Python Development Environments
-------------------------------

This part of the guide focus on the Python development environment,
and the best-practice tools that are available for writing Python code.

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv




Escribiendo Buen Código Python
------------------------------

Esta parte de la guía esta enfocada en las mejores prácticas para escribir código Python.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license



Guía de Escenarios para Aplicaciones Python
-------------------------------------------

Esta parte de la guía está enfocada en herramientas y módulos basado en diferentes escenarios.

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/ml
   scenarios/clibs


Entregar Buen Código Python
---------------------------

Esta parte de la guía esta enfocada en la entrega de tu código Python.

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


Additional Notes
----------------

Esta parte de la guía, que es en su mayoría texto, inicia con algunos
antecedentes acerca de Python, se enfoca en los siguientes pasos.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. note::
   Notes defined within all diatonic and chromatic musical scales have been
   intentionally excluded from this list of additional notes. Additionally,
   this note.


--------------------------------------

Notas de contribución e información legal (para los insteresados).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
